# fly.toml app configuration file generated for api-nitter on 2023-11-30T12:35:49+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-nitter"
primary_region = "waw"

[experimental]
  entrypoint = ["/src/entrypoint.sh"]

[build]
  image = "kristobalus/nitter:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
